# Generated by Django 3.2.8 on 2021-10-18 20:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20211018_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mini_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
