# Generated by Django 3.2.8 on 2021-10-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_about_mini_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mini_text',
            field=models.TextField(max_length=300),
        ),
    ]
